apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "job-reaper.fullname" . }}
  labels:
    {{- include "job-reaper.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "job-reaper.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
roleRef:
  kind: Role
  name: {{ include "job-reaper.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
