apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "job-reaper.fullname" . }}
  labels:
    {{- include "job-reaper.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "delete"]
