apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "job-reaper.serviceAccountName" . }}
  labels:
    {{- include "job-reaper.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
